### ISSUE TITLE
Plugin not running

### ISSUE THREAD

**Issue by megastef** [mfussenegger/crate-autocomplete#1]
Hi,

I have tried to install it (binary) and got this:
https://gist.github.com/megastef/ef8088aa59e5912dd0cd

Is the plugin still working with the current Crate version? 
Would it be possible to get an updated / compiled Version. 
I would like to use it with ACE editor - and you know this JavaScript Kids don't know what a compiler is ;)

Gruss
Stefan

**Comment by mfussenegger** [comment]
I didn't really update the plugin since crate 0.45 so chances are it doesn't work anymore.

The good news is that Crate will soon have an official server jar for plugin development. Once that is ready I'll update the plugin here.

**Comment by mfussenegger** [comment]
I've updated the plugin to work with crate 0.48.X
Can you try again?

Probably I should start to put out proper versioned releases and document  plugin-version / crate version compatibility once I've some time to do that =)

**Comment by megastef** [comment]
Thx!!! Will try it next days. The binary plugin has the same url?

**Comment by mfussenegger** [comment]
Yes the plugin url is the same

**Comment by megastef** [comment]
I tried today using "Crate 0.48.2" on Ubuntu (installed using ubuntu package):
- the simple wget according to readme did not work (jar file landed in plugins, checked permissions ...)
  restart ...
- Then I used again the command from my gist above (your old instructions?) 

```
bin/plugin -u http://dl.bintray.com/mfussenegger/maven/crate-autocomplete.jar -i mfussenegger/crate-autocomplete
```

and it landed in a sub-folder unzipped  - restarted crate ...

```
bin/plugin -l
Installed plugins:
    - crate-admin
    - crate-autocomplete
```

But the plugin is not loading (endpoint _sql_complete not working and no log message that it was loaded). Any idea? How can I debug the plugin loading?

**Comment by megastef** [comment]
java: 

```
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-1~deb7u1)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)
```

Crate 0.48.3:  

```
[2015-05-06 20:13:03,765][WARN ][plugins                  ] [Bloodtide] failed to load plugin from [file:/usr/share/crate/plugins/crate-autocomplete/es-plugin.properties]
org.elasticsearch.ElasticsearchException: Failed to load plugin class [io.crate.plugin.AutoCompletePlugin]
    at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:532)
    at org.elasticsearch.plugins.PluginsService.loadPluginsFromClasspath(PluginsService.java:407)
    at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:116)
Caused by: java.lang.UnsupportedClassVersionError: io/crate/plugin/AutoCompletePlugin : Unsupported major.minor version 52.0
    at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:509)
```

**Comment by megastef** [comment]
OK, got it running using Oracle Java 1.8.

**Comment by mfussenegger** [comment]
Awesome =)
